from . import industry_ea_code
from . import employment_type
from . import certification_standard
from . import auditor_category
from . import service_category
from . import unit_of_billing
from . import res_partner
from . import product_template
from . import sale_order
from . import sale_order_review
from . import sale_order_line
from . import account_move
from . import project
from . import project_task_mandays
from . import project_review
from . import project_atjf
from . import audit_document
from . import project_audit_plan
from . import project_audit_execution
from . import ir_ui_menu
from . import stock
from . import ir_actions_report
from . import application_annex
from . import ir_ui_view
