from . import industry_ea_code
from . import employment_type
from . import certification_standard
from . import auditor_category
from . import service_category
from . import unit_of_billing
from . import res_partner
from . import product_template
from . import sale_order
from . import account_move
from . import project
from . import stock
