from odoo import models


class SaleOrderLine(models.Model):
    _inherit = 'sale.order.line'

    def _timesheet_create_project_prepare_values(self):
        values = super()._timesheet_create_project_prepare_values()
        # Reuse the shared task stages. Without this, core seeds every freshly created
        # project with its own To Do / In Progress / Done / Cancelled set, which is what
        # made the same task show different stages depending on how it was opened.
        shared_stages = self.env['project.task.type'].search([('user_id', '=', False)])
        if shared_stages:
            values['type_ids'] = [(6, 0, shared_stages.ids)]
        return values

    def _timesheet_create_project(self):
        project = super()._timesheet_create_project()
        # A project generated by confirming an order is already live work, so it starts
        # In Progress instead of in the first ("To Do") stage.
        # sudo: project.stage_id is behind project.group_project_stages, which the
        # salesperson confirming the order does not necessarily have.
        in_progress = self.env.ref('project.project_project_stage_1', raise_if_not_found=False)
        if in_progress:
            project.sudo().stage_id = in_progress.id
        return project
